# Frontend Development Dockerfile
FROM node:22 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Update Npm to the latest version and install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose environment variable
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Command to run the frontend in development mode with hot reloading
CMD ["npm", "run", "dev"]
