volumes:
  postgres_data:

networks:
  CEM-KEA:
    driver: bridge

services:
  # Backend service with hot reload using Air
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - API_SERVER_PORT=8080
      - API_DATABASE_HOST=${API_DATABASE_HOST}
      - API_DATABASE_PORT=${API_DATABASE_PORT}
      - API_DATABASE_USER=${API_DATABASE_USER}
      - API_DATABASE_PASSWORD=${API_DATABASE_PASSWORD}
      - API_DATABASE_NAME=${API_DATABASE_NAME}
      - API_DATABASE_SSL_MODE=${API_DATABASE_SSL_MODE}
      - API_DATABASE_MIGRATE=${API_DATABASE_MIGRATE}
      - API_JWT_SECRET=${API_JWT_SECRET}
      - API_JWT_EXPIRATION=${API_JWT_EXPIRATION}
      - API_ENVIRONMENT=development
      - API_PAGINATION_LIMIT=${API_PAGINATION_LIMIT}
      - API_PAGINATION_OFFSET=${API_PAGINATION_OFFSET}
      - API_LOG_LEVEL=${API_LOG_LEVEL}
      - API_LOG_FORMAT=${API_LOG_FORMAT}
      - API_WEATHER_API_KEY=${API_WEATHER_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app:delegated
    command: air
    networks:
      - CEM-KEA
    depends_on:
      - db

  # Frontend service with Vite hot reload
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_URL=http://localhost:8080/api
    ports:
      - "5173:5173" # Vite default dev server port
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Mount node_modules inside the container to avoid rollup bug (https://github.com/vitejs/vite/discussions/15532)
    command: npm run dev -- --host
    networks:
      - CEM-KEA

  # Database service (Postgres)
  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - CEM-KEA
    ports:
      - "5432:5432"
