volumes:
  postgres_data:

networks:
  CEM-KEA:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: whoknows-backend:${IMAGE_TAG}
    container_name: backend
    environment:
      - API_SERVER_PORT=${API_SERVER_PORT}
      - API_DATABASE_HOST=${API_DATABASE_HOST}
      - API_DATABASE_PORT=${API_DATABASE_PORT}
      - API_DATABASE_USER=${API_DATABASE_USER}
      - API_DATABASE_PASSWORD=${API_DATABASE_PASSWORD}
      - API_DATABASE_NAME=${API_DATABASE_NAME}
      - API_DATABASE_SSL_MODE=${API_DATABASE_SSL_MODE}
      - API_DATABASE_MIGRATE=${API_DATABASE_MIGRATE}
      - API_JWT_SECRET=${API_JWT_SECRET}
      - API_JWT_EXPIRATION=${API_JWT_EXPIRATION}
      - API_APP_ENVIRONMENT=${API_APP_ENVIRONMENT}
      - DOCKER_ENV=true
    volumes:
      - ./backend/internal/database/pages.json:/app/internal/database/pages.json
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - CEM-KEA
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - CEM-KEA
    restart: unless-stopped