server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://51.20.246.124:3100/loki/api/v1/push

positions:
  filename: /var/log/positions/positions.yaml

scrape_configs:
  # Scrape backend logs from Docker container
  - job_name: "backend-logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Keep only logs from the backend container
      - source_labels: [__meta_docker_container_name]
        regex: backend
        action: keep
      # Set the instance label to the container name
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      # Set the job label to backend
      - target_label: job
        replacement: backend
    pipeline_stages:
      - docker: {}

  # Scrape Nginx logs from the Docker container
  - job_name: "nginx-logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Keep only logs from the nginx container
      - source_labels: [__meta_docker_container_name]
        regex: nginx
        action: keep
      # Set the instance label to the container name
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      # Set the job label to nginx
      - target_label: job
        replacement: nginx
    pipeline_stages:
      - docker: {}
    
