server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: https://monitor.cemdev.dk/loki/api/v1/push
    tls_config:
      insecure_skip_verify: false

positions:
  filename: /var/log/positions/positions.yaml

scrape_configs:
  # Backend logs configuration
  - job_name: "backend-logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: backend
        action: keep
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      - target_label: job
        replacement: backend
    pipeline_stages:
      - docker: {}
      - labels:
          job: backend
          env: production
          host: "primary-system"

  # Nginx logs configuration
  - job_name: "nginx-logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: nginx
        action: keep
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      - target_label: job
        replacement: nginx
    pipeline_stages:
      - docker: {}
      - labels:
          job: nginx
          env: production
          host: "primary-system"
    
