server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://${MONITOR_IP}:3100/loki/api/v1/push

positions:
  filename: /var/log/positions/positions.yaml

scrape_configs:
  # Scrape backend logs
  - job_name: "backend-logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Target only the backend container by its container name
      - source_labels: [__meta_docker_container_name]
        regex: "/backend"
        action: keep
      - source_labels: [__meta_docker_container_name]
        target_label: instance
        replacement: backend-instance
    pipeline_stages:
      - docker: {}
    labels:
      job: backend

  # Scrape Nginx logs
  - job_name: "nginx-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          instance: nginx-instance
          __path__: /var/log/nginx/*.log
