definitions:
  handlers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handlers.LoginResponse:
    properties:
      token:
        type: string
    type: object
  handlers.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  handlers.SearchResponse:
    properties:
      data:
        items:
          additionalProperties: true
          type: object
        type: array
    type: object
  handlers.WeatherResponse:
    properties:
      data:
        additionalProperties: true
        type: object
    type: object
info:
  contact: {}
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Login with username and password
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginResponse'
        "400":
          description: Invalid request body
          schema:
            type: string
        "401":
          description: Invalid username or password
          schema:
            type: string
  /api/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User data
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            type: string
        "400":
          description: Validation error
          schema:
            type: string
        "500":
          description: Failed to create user
          schema:
            type: string
  /api/search:
    get:
      description: Search for pages by content
      parameters:
      - description: Search query
        in: query
        name: q
        required: true
        type: string
      - description: Language filter
        in: query
        name: language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SearchResponse'
        "400":
          description: Search query (q) is required
          schema:
            type: string
        "500":
          description: Search query failed
          schema:
            type: string
  /api/weather:
    get:
      description: Get weather information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.WeatherResponse'
        "500":
          description: Failed to fetch weather data
          schema:
            type: string
swagger: "2.0"
