// maps weather description from openweathermap to emoji
export const weatherToEmoji: { [key: string]: string } = {
  "clear sky": "☀️",
  "few clouds": "🌤",
  "scattered clouds": "⛅️",
  "broken clouds": "🌥",
  "overcast clouds": "☁️",
  mist: "🌫️",
  smoke: "🌫️",
  haze: "🌫️",
  "sand/ dust whirls": "🌫️",
  fog: "🌫️",
  sand: "🌫️",
  dust: "🌫️",
  "volcanic ash": "🌫️",
  squalls: "🌫️",
  tornado: "🌪️",
  rain: "🌧️",
  "light rain": "🌦",
  "moderate rain": "🌧️",
  "heavy intensity rain": "🌧️",
  "very heavy rain": "🌧️",
  "extreme rain": "🌧️",
  "freezing rain": "🌧️❄️",
  "light intensity shower rain": "🌧️",
  "shower rain": "🌧️",
  "heavy intensity shower rain": "🌧️",
  "ragged shower rain": "🌧️",
  "heavy rain": "🌧️",
  drizzle: "🌦",
  "light intensity drizzle": "🌦",
  "drizzle rain": "🌦",
  "heavy intensity drizzle": "🌧️",
  "light intensity drizzle rain": "🌧️",
  "heavy intensity drizzle rain": "🌧️",
  "shower rain and drizzle": "🌧️",
  "heavy shower rain and drizzle": "🌧️",
  "shower drizzle": "🌧️",
  thunderstorm: "⛈️",
  "thunderstorm with light rain": "⛈️🌧️",
  "thunderstorm with rain": "⛈️🌧️",
  "thunderstorm with heavy rain": "⛈️🌧️",
  "light thunderstorm": "⛈️",
  "heavy thunderstorm": "⛈️",
  "ragged thunderstorm": "⛈️",
  "thunderstorm with light drizzle": "⛈️🌧️",
  "thunderstorm with drizzle": "⛈️🌧",
  "thunderstorm with heavy drizzle": "⛈️🌧️",
  snow: "🌨️",
  "light snow": "🌨️",
  "heavy snow": "❄️",
  sleet: "🌧️❄️",
  "light shower sleet": "🌧️❄️",
  "shower sleet": "🌧️❄️",
  "light rain and snow": "🌨️",
  "rain and snow": "🌨️",
  "light shower snow": "🌨️",
  "shower snow": "🌨️",
  "heavy shower snow": "🌨️",
  hail: "🌨️",
  windy: "💨"
};

// formats temperature from kelvin to celsius (openweathermap returns temperature in kelvin)
export function formatTemperature(tempInKelvin: number): string {
  return (tempInKelvin - 273.15).toFixed(1) + " °C";
}
