Server:
  Port: 8080
Database:
  FilePath: ./internal/database/whoknows.db
  Migrate: false
  Seed: false
  SeedFilePath: ./internal/database/pages.json
Pagination:
  Limit: 10
  Offset: 0
Log:
  Level: debug
  Format: text
